import { Product } from '@/redux/reducers/products/types';

export const PROFILE_PIC = 'https://xsgames.co/randomusers/avatar.php?g=pixel&key=1';

export const CATEGORIES = [
  { id: 1, name: 'Paleta de agua' },
  { id: 2, name: 'Paleta de crema' },
  { id: 3, name: 'Cubierta de chocolate' },
  { id: 4, name: 'Helado' },
  { id: 5, name: 'Nieve' },
  { id: 6, name: 'Sandwich' },
  { id: 7, name: 'Bolis' },
  { id: 8, name: 'Materia prima' },
  { id: 9, name: 'Paleta mini agua' },
  { id: 10, name: 'Paleta mini crema' },
  { id: 11, name: 'Pastes' },
];

export const EXTRA_ITEM_BASE = {
  name: 'Extra',
  category_id: 7, // extra
  product_id: 0,
  retail_price: 0,
  status: 2,
  stock: 0,
  wholesale_price: 0,
  created_at: new Date(),
  description: 'Producto pivote',
};

export const PRODUCTS_MOCK: Product[] = [
  {
    name: 'Paleta de vainilla',
    category_id: 3,
    product_id: 1,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 0,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Paleta de fresa',
    category_id: 3,
    product_id: 2,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Paleta de coco',
    category_id: 3,
    product_id: 3,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Paleta de chocolate',
    category_id: 3,
    product_id: 4,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Limon Grande',
    category_id: 1,
    product_id: 5,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Guayaba Grande',
    category_id: 1,
    product_id: 6,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Guayaba Ch',
    category_id: 1,
    product_id: 7,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Limon Ch',
    category_id: 1,
    product_id: 8,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Grosella Ch',
    category_id: 1,
    product_id: 9,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Grosella Gr',
    category_id: 1,
    product_id: 19,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Mango Gr',
    category_id: 1,
    product_id: 10,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Mango CH',
    category_id: 1,
    product_id: 11,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Mango CH chile',
    category_id: 1,
    product_id: 21,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Mango GR chile',
    category_id: 1,
    product_id: 12,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Piña CH chile',
    category_id: 1,
    product_id: 13,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 110,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
  {
    name: 'Piña GR chile',
    category_id: 1,
    product_id: 14,
    retail_price: 5,
    status: 1,
    stock: 10,
    wholesale_price: 10,
    created_at: new Date(),
    description: 'Paleta de vainilla',
  },
];
