export const PERMISSIONS = {
  pos: {
    switch_prices: true,
    apply_discount: true,
    apply_shipping: true,
    add_manual_item: true,
    add_custom_price: true,
  },
  products: {
    view_catalog: true,
    add_product: true,
    edit_product: true,
    delete_product: true,
    show_in_catalog: true,
    // update_stock: true,
    // update_price: true,
    update_image: true,
  },
  online_store: {
    view_online_store: true,
    edit_online_store: true,
  },
  customers: {
    view_customers: true,
    add_customer: true,
    edit_customer: true,
    delete_customer: true,
  },
  sales: {
    view_sales: true,
    add_sale: true,
    edit_sale: true,
    delete_sale: true,
    download_receipt: true,
  },
  company: {
    view_company: true,
    edit_company: true,
  },
  branches: {
    view_branches: true,
    add_branch: true,
    edit_branch: true,
    delete_branch: true,
  },
  cash_registers: {
    view_current_cash_cut: true,
    view_history_cash_cuts: true,
    open_cash_cut: true,
    make_cash_cut: true,
    make_cash_cut_operation: true,
    view_cash_registers: true,
    add_cash_register: true,
    edit_cash_register: true,
    delete_cash_register: true,
  },
  reports: {
    // view_reports: true,
    view_sales_report: true,
    view_products_report: true,
    view_customers_report: true,
  },
  price_list: {
    view_price_list: true,
    add_price: true,
    edit_price: true,
    delete_price: true,
  },
  categories: {
    view_categories: true,
    add_category: true,
    edit_category: true,
    delete_category: true,
  },
  sizes: {
    view_sizes: true,
    add_size: true,
    edit_size: true,
    delete_size: true,
  },
  units: {
    view_units: true,
    add_unit: true,
    edit_unit: true,
    delete_unit: true,
  },
  expenses: {
    view_expenses: true,
    add_expense: true,
    edit_expense: true,
    delete_expense: true,
  },
};

export const PERMISSIONS_DENIED = {
  pos: {
    switch_prices: false,
    apply_discount: false,
    apply_shipping: false,
    add_manual_item: false,
    add_custom_price: false,
  },
  products: {
    view_catalog: false,
    add_product: false,
    edit_product: false,
    delete_product: false,
    show_in_catalog: false,
    update_stock: false,
    update_price: false,
    update_image: false,
  },
  online_store: {
    view_online_store: false,
    edit_online_store: false,
  },
  customers: {
    view_customers: false,
    add_customer: false,
    edit_customer: false,
    delete_customer: false,
  },
  sales: {
    view_sales: false,
    add_sale: false,
    edit_sale: false,
    delete_sale: false,
    download_receipt: false,
  },
  company: {
    view_company: false,
    edit_company: false,
  },
  branches: {
    view_branches: false,
    add_branch: false,
    edit_branch: false,
    delete_branch: false,
  },
  reports: {
    // view_reports: false,
    view_sales_report: false,
    view_products_report: false,
    view_customers_report: false,
  },
  cash_registers: {
    view_current_cash_cut: false,
    view_history_cash_cuts: false,
    open_cash_cut: false,
    make_cash_cut: false,
    make_cash_cut_operation: false,
    view_cash_registers: false,
    add_cash_register: false,
    edit_cash_register: false,
    delete_cash_register: false,
  },
  price_list: {
    view_price_list: false,
    add_price: false,
    edit_price: false,
    delete_price: false,
  },
  categories: {
    view_categories: false,
    add_category: false,
    edit_category: false,
    delete_category: false,
  },
  sizes: {
    view_sizes: false,
    add_size: false,
    edit_size: false,
    delete_size: false,
  },
  units: {
    view_units: false,
    add_unit: false,
    edit_unit: false,
    delete_unit: false,
  },
  expenses: {
    view_expenses: false,
    add_expense: false,
    edit_expense: false,
    delete_expense: false,
  },
};

export const PERMISSION_NAMES = {
  pos: 'Punto de venta',
  products: 'Productos',
  customers: 'Clientes',
  sales: 'Ventas',
  company: 'Empresa',
  branches: 'Sucursales',
  cash_registers: 'Cajas',
  price_list: 'Lista de precios',
  categories: 'Categorías',
  sizes: 'Tamaños',
  units: 'Unidades',
  expenses: 'Gastos',
  reports: 'Reportes',

  online_store: 'Tienda en línea',
  view_online_store: 'Ver tienda en línea',
  edit_online_store: 'Editar tienda en línea',

  view_reports: 'Ver reportes',
  view_sales_report: 'Ver reporte de ventas',
  view_products_report: 'Ver reporte de productos',
  view_customers_report: 'Ver reporte de clientes',

  switch_prices: 'Cambiar precios',
  apply_discount: 'Aplicar descuento',
  apply_shipping: 'Aplicar envío',
  add_manual_item: 'Agregar producto manual',
  add_custom_price: 'Agregar precio personalizado',
  view_catalog: 'Ver catálogo',
  add_product: 'Agregar producto',
  edit_product: 'Editar producto',
  delete_product: 'Eliminar producto',
  show_in_catalog: 'Mostrar en catálogo',
  update_stock: 'Actualizar stock',
  update_price: 'Actualizar precio',
  update_image: 'Actualizar imagen',
  view_customers: 'Ver clientes',
  add_customer: 'Agregar cliente',
  edit_customer: 'Editar cliente',
  delete_customer: 'Eliminar cliente',
  view_sales: 'Ver ventas',
  add_sale: 'Agregar venta',
  edit_sale: 'Editar venta',
  delete_sale: 'Eliminar venta',
  download_receipt: 'Descargar recibo',
  view_company: 'Ver información de la empresa',
  edit_company: 'Editar información de la empresa',
  view_branches: 'Ver sucursales',
  add_branch: 'Agregar sucursal',
  edit_branch: 'Editar sucursal',
  delete_branch: 'Eliminar sucursal',
  view_current_cash_cut: 'Ver corte de caja actual',
  view_history_cash_cuts: 'Ver historial de cortes de caja',
  open_cash_cut: 'Abrir caja',
  make_cash_cut: 'Realizar corte de caja',
  make_cash_cut_operation: 'Realizar operación de corte de caja',
  view_cash_registers: 'Ver cajas',
  add_cash_register: 'Agregar caja',
  edit_cash_register: 'Editar caja',
  delete_cash_register: 'Eliminar caja',
  view_price_list: 'Ver lista de precios',
  add_price: 'Agregar precio',
  edit_price: 'Editar precio',
  delete_price: 'Eliminar precio',
  view_categories: 'Ver categorías',
  add_category: 'Agregar categoría',
  edit_category: 'Editar categoría',
  delete_category: 'Eliminar categoría',
  view_sizes: 'Ver tamaños',
  add_size: 'Agregar tamaño',
  edit_size: 'Editar tamaño',
  delete_size: 'Eliminar tamaño',
  view_units: 'Ver unidades',
  add_unit: 'Agregar unidad',
  edit_unit: 'Editar unidad',
  delete_unit: 'Eliminar unidad',
  view_users: 'Ver usuarios',
  add_user: 'Agregar usuario',
  edit_user: 'Editar usuario',
  delete_user: 'Eliminar usuario',
  view_expenses: 'Ver gastos',
  add_expense: 'Agregar gasto',
  edit_expense: 'Editar gasto',
  delete_expense: 'Eliminar gasto',
};

export type PermissionsType = {
  [key: string]: {
    [key: string]: boolean;
  };
};
