export const PERMISSIONS = {
  pos: {
    add_sale: { value: true, scope: [1, 2, 3, 4] },
    switch_prices: { value: true, scope: [1, 2, 3, 4] },
    apply_discount: { value: true, scope: [1, 2, 3, 4] },
    apply_shipping: { value: true, scope: [1, 2, 3, 4] },
    add_manual_item: { value: true, scope: [1, 2, 3, 4] },
    add_custom_price: { value: true, scope: [1, 2, 3, 4] },
    add_customer_to_sale: { value: true, scope: [1, 2, 3, 4] },
  },
  sales: {
    view_sales: { value: true, scope: [1, 2, 3, 4] },
    edit_sale: { value: true, scope: [1, 2, 3, 4] },
    delete_sale: { value: true, scope: [1, 2, 3, 4] },
    download_receipt: { value: true, scope: [1, 2, 3, 4] },
  },
  products: {
    view_catalog: { value: true, scope: [1, 2, 3, 4] },
    add_product: { value: true, scope: [1, 2, 3, 4] },
    edit_product: { value: true, scope: [1, 2, 3, 4] },
    delete_product: { value: true, scope: [1, 2, 3, 4] },
    show_in_catalog: { value: true, scope: [1, 2, 3, 4] },
    // update_stock: {value: true, scope: [1, 2, 3, 4]},
    // update_price: {value: true, scope: [1, 2, 3, 4]},
    update_image: { value: true, scope: [1, 2, 3, 4] },
  },
  online_store: {
    view_online_store: { value: true, scope: [1, 2, 3, 4] },
    edit_online_store: { value: true, scope: [1, 2, 3, 4] },
  },
  customers: {
    view_customers: { value: true, scope: [1, 2, 3, 4] },
    add_customer: { value: true, scope: [1, 2, 3, 4] },
    edit_customer: { value: true, scope: [1, 2, 3, 4] },
    delete_customer: { value: true, scope: [1, 2, 3, 4] },
  },
  company: {
    // view_company: { value: true, scope: [1, 2, 3, 4] },
    edit_company: { value: true, scope: [1, 2, 3, 4] },
  },
  branches: {
    view_branches: { value: true, scope: [1, 2, 3, 4] },
    add_branch: { value: true, scope: [1, 2, 3, 4] },
    edit_branch: { value: true, scope: [1, 2, 3, 4] },
    delete_branch: { value: true, scope: [1, 2, 3, 4] },
  },
  cash_registers: {
    view_current_cash_cut: { value: true, scope: [1, 2, 3, 4] },
    view_history_cash_cuts: { value: true, scope: [1, 2, 3, 4] },
    open_cash_cut: { value: true, scope: [1, 2, 3, 4] },
    make_cash_cut: { value: true, scope: [1, 2, 3, 4] },
    make_cash_cut_operation: { value: true, scope: [1, 2, 3, 4] },
    view_cash_registers: { value: true, scope: [1, 2, 3, 4] },
    add_cash_register: { value: true, scope: [1, 2, 3, 4] },
    edit_cash_register: { value: true, scope: [1, 2, 3, 4] },
    delete_cash_register: { value: true, scope: [1, 2, 3, 4] },
  },
  reports: {
    // view_reports: {value: true, scope: [1, 2, 3, 4]},
    view_sales_report: { value: true, scope: [1, 2, 3, 4] },
    view_products_report: { value: true, scope: [1, 2, 3, 4] },
    view_customers_report: { value: true, scope: [1, 2, 3, 4] },
    view_expenses_report: { value: true, scope: [1, 2, 3, 4] },
    view_profit_report: { value: true, scope: [1, 2, 3, 4] },
  },
  price_list: {
    view_price_list: { value: true, scope: [1, 2, 3, 4] },
    add_price: { value: true, scope: [1, 2, 3, 4] },
    edit_price: { value: true, scope: [1, 2, 3, 4] },
    delete_price: { value: true, scope: [1, 2, 3, 4] },
  },
  categories: {
    view_categories: { value: true, scope: [1, 2, 3, 4] },
    add_category: { value: true, scope: [1, 2, 3, 4] },
    edit_category: { value: true, scope: [1, 2, 3, 4] },
    delete_category: { value: true, scope: [1, 2, 3, 4] },
  },
  sizes: {
    view_sizes: { value: true, scope: [1, 2, 3, 4] },
    add_size: { value: true, scope: [1, 2, 3, 4] },
    edit_size: { value: true, scope: [1, 2, 3, 4] },
    delete_size: { value: true, scope: [1, 2, 3, 4] },
  },
  units: {
    view_units: { value: true, scope: [1, 2, 3, 4] },
    add_unit: { value: true, scope: [1, 2, 3, 4] },
    edit_unit: { value: true, scope: [1, 2, 3, 4] },
    delete_unit: { value: true, scope: [1, 2, 3, 4] },
  },
  expenses: {
    view_expenses: { value: true, scope: [1, 2, 3, 4] },
    add_expense: { value: true, scope: [1, 2, 3, 4] },
    edit_expense: { value: true, scope: [1, 2, 3, 4] },
    delete_expense: { value: true, scope: [1, 2, 3, 4] },
    upload_evidence: { value: true, scope: [1, 2, 3, 4] },
  },
};

export const PERMISSIONS_DENIED = {
  pos: {
    add_sale: { value: false, scope: [1, 2, 3, 4] },
    switch_prices: { value: false, scope: [1, 2, 3, 4] },
    apply_discount: { value: false, scope: [1, 2, 3, 4] },
    apply_shipping: { value: false, scope: [1, 2, 3, 4] },
    add_manual_item: { value: false, scope: [1, 2, 3, 4] },
    add_custom_price: { value: false, scope: [1, 2, 3, 4] },
    add_customer_to_sale: { value: false, scope: [1, 2, 3, 4] },
  },
  sales: {
    view_sales: { value: false, scope: [1, 2, 3, 4] },
    edit_sale: { value: false, scope: [1, 2, 3, 4] },
    delete_sale: { value: false, scope: [1, 2, 3, 4] },
    download_receipt: { value: false, scope: [1, 2, 3, 4] },
  },
  products: {
    view_catalog: { value: false, scope: [1, 2, 3, 4] },
    add_product: { value: false, scope: [1, 2, 3, 4] },
    edit_product: { value: false, scope: [1, 2, 3, 4] },
    delete_product: { value: false, scope: [1, 2, 3, 4] },
    show_in_catalog: { value: false, scope: [1, 2, 3, 4] },
    update_stock: { value: false, scope: [1, 2, 3, 4] },
    update_price: { value: false, scope: [1, 2, 3, 4] },
    update_image: { value: false, scope: [1, 2, 3, 4] },
  },
  online_store: {
    view_online_store: { value: false, scope: [1, 2, 3, 4] },
    edit_online_store: { value: false, scope: [1, 2, 3, 4] },
  },
  customers: {
    view_customers: { value: false, scope: [1, 2, 3, 4] },
    add_customer: { value: false, scope: [1, 2, 3, 4] },
    edit_customer: { value: false, scope: [1, 2, 3, 4] },
    delete_customer: { value: false, scope: [1, 2, 3, 4] },
  },
  company: {
    view_company: { value: false, scope: [1, 2, 3, 4] },
    edit_company: { value: false, scope: [1, 2, 3, 4] },
  },
  branches: {
    view_branches: { value: false, scope: [1, 2, 3, 4] },
    add_branch: { value: false, scope: [1, 2, 3, 4] },
    edit_branch: { value: false, scope: [1, 2, 3, 4] },
    delete_branch: { value: false, scope: [1, 2, 3, 4] },
  },
  reports: {
    // view_reports: { value: false, scope: [1, 2, 3, 4] },
    view_sales_report: { value: false, scope: [1, 2, 3, 4] },
    view_products_report: { value: false, scope: [1, 2, 3, 4] },
    view_customers_report: { value: false, scope: [1, 2, 3, 4] },
    view_expenses_report: { value: true, scope: [1, 2, 3, 4] },
    view_profit_report: { value: true, scope: [1, 2, 3, 4] },
  },
  cash_registers: {
    view_current_cash_cut: { value: false, scope: [1, 2, 3, 4] },
    view_history_cash_cuts: { value: false, scope: [1, 2, 3, 4] },
    open_cash_cut: { value: false, scope: [1, 2, 3, 4] },
    make_cash_cut: { value: false, scope: [1, 2, 3, 4] },
    make_cash_cut_operation: { value: false, scope: [1, 2, 3, 4] },
    view_cash_registers: { value: false, scope: [1, 2, 3, 4] },
    add_cash_register: { value: false, scope: [1, 2, 3, 4] },
    edit_cash_register: { value: false, scope: [1, 2, 3, 4] },
    delete_cash_register: { value: false, scope: [1, 2, 3, 4] },
  },
  price_list: {
    view_price_list: { value: false, scope: [1, 2, 3, 4] },
    add_price: { value: false, scope: [1, 2, 3, 4] },
    edit_price: { value: false, scope: [1, 2, 3, 4] },
    delete_price: { value: false, scope: [1, 2, 3, 4] },
  },
  categories: {
    view_categories: { value: false, scope: [1, 2, 3, 4] },
    add_category: { value: false, scope: [1, 2, 3, 4] },
    edit_category: { value: false, scope: [1, 2, 3, 4] },
    delete_category: { value: false, scope: [1, 2, 3, 4] },
  },
  sizes: {
    view_sizes: { value: false, scope: [1, 2, 3, 4] },
    add_size: { value: false, scope: [1, 2, 3, 4] },
    edit_size: { value: false, scope: [1, 2, 3, 4] },
    delete_size: { value: false, scope: [1, 2, 3, 4] },
  },
  units: {
    view_units: { value: false, scope: [1, 2, 3, 4] },
    add_unit: { value: false, scope: [1, 2, 3, 4] },
    edit_unit: { value: false, scope: [1, 2, 3, 4] },
    delete_unit: { value: false, scope: [1, 2, 3, 4] },
  },
  expenses: {
    view_expenses: { value: false, scope: [1, 2, 3, 4] },
    add_expense: { value: false, scope: [1, 2, 3, 4] },
    edit_expense: { value: false, scope: [1, 2, 3, 4] },
    delete_expense: { value: false, scope: [1, 2, 3, 4] },
    upload_evidence: { value: false, scope: [1, 2, 3, 4] },
  },
};

export const PERMISSION_NAMES = {
  pos: 'Punto de venta',
  products: 'Productos',
  customers: 'Clientes',
  sales: 'Ventas',
  company: 'Empresa',
  branches: 'Sucursales',
  cash_registers: 'Cajas',
  price_list: 'Lista de precios',
  categories: 'Categorías',
  sizes: 'Tamaños',
  units: 'Unidades',
  expenses: 'Gastos',
  reports: 'Reportes',

  online_store: 'Tienda en línea',
  view_online_store: 'Acceso al módulo de "Tienda en línea"',
  edit_online_store: 'Editar tienda en línea',

  view_reports: 'Ver reportes',
  view_sales_report: 'Ver reporte de ventas',
  view_products_report: 'Ver reporte de productos',
  view_customers_report: 'Ver reporte de clientes',
  view_expenses_report: 'Ver reporte de gastos',
  view_profit_report: 'Ver reporte de ganancias',

  switch_prices: 'Cambiar precios por tipo de cliente',
  apply_discount: 'Aplicar descuento a la venta',
  apply_shipping: 'Aplicar envío a la venta',
  add_manual_item: 'Agregar producto manual a la venta',
  add_custom_price: 'Agregar precio personalizado a un producto',
  add_customer_to_sale: 'Agregar cliente a la venta',

  view_catalog: 'Ver inventario de productos',
  add_product: 'Agregar producto al inventario',
  edit_product: 'Editar producto',
  delete_product: 'Eliminar producto del inventario',
  show_in_catalog: 'Mostrar opción para publicar producto en catálogo en línea',
  update_stock: 'Actualizar stock de producto',
  update_price: 'Actualizar precio de producto',
  update_image: 'Actualizar imagen de producto',

  view_customers: 'Ver clientes',
  add_customer: 'Agregar cliente',
  edit_customer: 'Editar cliente',
  delete_customer: 'Eliminar cliente',

  view_sales: 'Ver ventas realizadas',
  add_sale: 'Registrar venta',
  edit_sale: 'Editar venta registrada',
  delete_sale: 'Eliminar venta registrada',
  download_receipt: 'Descargar nota de venta',

  view_company: 'Ver información de la empresa',
  edit_company: 'Editar información de la empresa',

  view_branches: 'Acceso al módulo de "Sucursales"',
  add_branch: 'Agregar sucursal',
  edit_branch: 'Editar sucursal',
  delete_branch: 'Eliminar sucursal',

  view_cash_registers: 'Acceso al módulo de "Cajas"',
  view_current_cash_cut: 'Ver corte de caja actual',
  view_history_cash_cuts: 'Ver historial de cortes de caja',
  open_cash_cut: 'Iniciar un corte de caja',
  make_cash_cut: 'Realizar corte de caja',
  make_cash_cut_operation: 'Registrar ingresos/egresos en corte de caja',
  add_cash_register: 'Agregar nueva caja a una sucursal',
  edit_cash_register: 'Editar nombre de caja',
  delete_cash_register: 'Eliminar caja de una sucursal',

  view_price_list: 'Acceso al módulo "Lista de precios"',
  add_price: 'Agregar nuevo precio',
  edit_price: 'Editar precio',
  delete_price: 'Eliminar precio',

  view_categories: 'Acceso al módulo "Categorías"',
  add_category: 'Agregar categoría',
  edit_category: 'Editar categoría',
  delete_category: 'Eliminar categoría',

  view_sizes: 'Acceso al módulo "Tamaños"',
  add_size: 'Agregar tamaño',
  edit_size: 'Editar tamaño',
  delete_size: 'Eliminar tamaño',

  view_units: 'Acceso al módulo "Unidades"',
  add_unit: 'Agregar unidad',
  edit_unit: 'Editar unidad',
  delete_unit: 'Eliminar unidad',

  view_users: 'Acceso al módulo "Usuarios"',
  add_user: 'Agregar usuario',
  edit_user: 'Editar usuario',
  delete_user: 'Eliminar usuario',

  view_expenses: 'Acceso al módulo "Gastos"',
  add_expense: 'Registrar gasto',
  edit_expense: 'Editar gasto',
  delete_expense: 'Eliminar gasto',
  upload_evidence: 'Subir evidencia de gasto',
};

export type PermissionsType = {
  [key: string]: {
    [key: string]: { value: boolean; scope: number[] };
  };
};
